server:
  port: 9998

spring:
  application:
    name: langrisser

  datasource:
#    url: jdbc:h2:mem:langrisser
#    url: jdbc:h2:file:./langrisser;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:./langrisser3;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  enable-querydsl: false

google:
  sheet:
    base-url: https://docs.google.com/spreadsheets/d/19eLjTpcTDSZLiyTAMJGSBXJkWLAmq7QYs3t9qWEGv40
    csv-path: /export?format=csv&gid=0
